[project]
name = "data-explorer-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "John C. Hood II", email = "hood.astro@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
data-explorer-agents = "data_explorer_agents:main"

[build-system]
requires = ["uv_build>=0.10.10,<0.11.0"]
build-backend = "uv_build"
